#!/usr/bin/env bash

source "$(realpath $(dirname "${0}")/..)/scripts/common"

docker run -ti --rm --name "${DOCKER_NAME}-${PORT}" \
 -e SET_DDF_COVER_DB=${SET_DDF_COVER_DB} \
 -e RAWREPO_RECORD_SERVICE_URL=${RAWREPO_RECORD_SERVICE_URL} \
 -e OAUTH2_CLIENT_ID=${OAUTH2_CLIENT_ID} \
 -e OAUTH2_CLIENT_SECRET=${OAUTH2_CLIENT_SECRET} \
 -e JAVA_MAX_HEAP_SIZE=${JAVA_MAX_HEAP_SIZE} \
 -e LOG_FORMAT=${LOG_FORMAT} \
 -p "${PORT}:8080" \
 "${DOCKER_REPOSITORY}:devel"
