#!/usr/bin/env bash

source "$(realpath $(dirname "${0}")/..)/scripts/common"

docker run -ti --rm --name "${DOCKER_NAME}-database" \
  -e "POSTGRES_DB=pg_queue" \
  -e "POSTGRES_USER=${USER}" \
  -e "POSTGRES_PASSWORD=${USER}" \
  -e "LOG_FORMAT=${LOG_FORMAT}" \
  -p "5432:5432" \
  "docker.dbc.dk/dbc-postgres-13:latest"
